spring.application.name=api-gateway
server.port=8080
eureka.client.register-with-eureka= true
eureka.client.fetch-registry= true

jwt.secret= my-super-secret-key-which-is-very-long
jwt.expiration= 3600000